version: '3'
services:
  quill:
    container_name: quill
    build:
      context: ./quill
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:6100
    environment:
      - CHOKIDAR_USEPOLLING=true
  draft:
    container_name: draft
    build:
        context: ./draft
        dockerfile: Dockerfile
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
        - 3000:6200
    environment:
        - CHOKIDAR_USEPOLLING=true