version: '3'
services:
  quill:
    container_name: quill
    build:
      context: ./quill
      dockerfile: Dockerfile
    volumes:
      - './quill:/app'
      - '/app/node_modules'
    ports:
      - "6100:81"
    environment:
      - CHOKIDAR_USEPOLLING=true
  draft:
    container_name: draft
    build:
      context: ./draft
      dockerfile: Dockerfile
    volumes:
      - './draft:/app'
      - '/app/node_modules'
    ports:
      - "6200:82"
    environment:
      - CHOKIDAR_USEPOLLING=true
